#!/usr/bin/bash

sbcl --noinform \
--load lib/package.lisp \
--load lib/split-sequence.lisp \
--load lib/sean.lisp \
--load testing/lisp-unit.lisp \
--load testing/sean-test.lisp \
--eval $"(in-package :sean-test)" \
--eval $"(progn (run-tests :all) (sb-ext:exit))"
